description "Defcoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env DEFCOIND_BIN="/usr/bin/defcoind"
env DEFCOIND_USER="defcoin"
env DEFCOIND_GROUP="defcoin"
env DEFCOIND_PIDDIR="/var/run/defcoind"
# upstart can't handle variables constructed with other variables
env DEFCOIND_PIDFILE="/var/run/defcoind/defcoind.pid"
env DEFCOIND_CONFIGFILE="/etc/defcoin/defcoin.conf"
env DEFCOIND_DATADIR="/var/lib/defcoind"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # defcoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$DEFCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run defcoind."
        echo "The setting must appear in $DEFCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Defcoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$DEFCOIND_PIDDIR"
    chmod 0755 "$DEFCOIND_PIDDIR"
    chown $DEFCOIND_USER:$DEFCOIND_GROUP "$DEFCOIND_PIDDIR"
    chown $DEFCOIND_USER:$DEFCOIND_GROUP "$DEFCOIND_CONFIGFILE"
    chmod 0660 "$DEFCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$DEFCOIND_PIDFILE" \
    --chuid $DEFCOIND_USER:$DEFCOIND_GROUP \
    --exec "$DEFCOIND_BIN" \
    -- \
    -pid="$DEFCOIND_PIDFILE" \
    -conf="$DEFCOIND_CONFIGFILE" \
    -datadir="$DEFCOIND_DATADIR" \
    -disablewallet \
    -daemon
