#!/usr/bin/env bash
#
#  defcoind The defcoin core server.
#
#
# chkconfig: 345 80 20
# description: defcoind
# processname: defcoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/defcoind, see below
if [ -f /etc/sysconfig/defcoind ]; then
        . /etc/sysconfig/defcoind
fi

RETVAL=0

prog=defcoind
# you can override the lockfile via DEFCOIND_LOCKFILE in /etc/sysconfig/defcoind
lockfile=${DEFCOIND_LOCKFILE-/var/lock/subsys/defcoind}

# defcoind defaults to /usr/bin/defcoind, override with DEFCOIND_BIN
defcoind=${DEFCOIND_BIN-/usr/bin/defcoind}

# defcoind opts default to -disablewallet, override with DEFCOIND_OPTS
defcoind_opts=${DEFCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $defcoind $defcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
